apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: full-stack
    app-module: postgres-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: full-stack
      app-module: postgres-db
  template:
    metadata:
      name: postgres-db
      labels:
        app: full-stack
        app-module: postgres-db
    spec:
      containers:
        - name: postgres
          image: postgres
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: full-stack-config-map
            - secretRef:
                name: full-stack-secret